apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    purpose: observability
---
apiVersion: v1
kind: Namespace
metadata:
  name: chaos-testing
  labels:
    purpose: chaos-mesh
---
apiVersion: v1
kind: Namespace
metadata:
  name: litmus
  labels:
    purpose: litmus-chaos
---
apiVersion: v1
kind: Namespace
metadata:
  name: gremlin
  labels:
    purpose: gremlin-chaos
---
apiVersion: v1
kind: Namespace
metadata:
  name: social-network
  labels:
    purpose: deathstarbench
    chaos-mesh.org/inject: "true"
